# Generated by Django 4.2.1 on 2023-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_raspisanie_options_rename_day_raspisanie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('zaniatia', models.TextField(verbose_name='Занятия')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
    ]
