# Generated by Django 4.2.1 on 2023-05-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rools',
            name='zaniatia',
        ),
    ]
