# Generated by Django 4.2.1 on 2023-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_rools_zaniatia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('kartinka', models.ImageField(upload_to='images', verbose_name='Картинка')),
                ('opisanie', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Афиша',
                'verbose_name_plural': 'Афиши',
            },
        ),
    ]
