# Generated by Django 4.2.1 on 2023-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_posters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Запрет',
                'verbose_name_plural': 'Запреты',
            },
        ),
        migrations.AlterField(
            model_name='posters',
            name='kartinka',
            field=models.ImageField(upload_to='media', verbose_name='Картинка'),
        ),
    ]
