# Generated by Django 4.2 on 2023-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rasporiadok_alter_rools_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raspisanie',
        ),
        migrations.AlterField(
            model_name='zapret',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
