# Generated by Django 4.2 on 2023-05-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_raspisanie_alter_zapret_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='posters',
            name='kartinka',
        ),
    ]
