# Generated by Django 4.2 on 2023-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_image_remove_posters_kartinka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('vremia', models.TextField(max_length=50, verbose_name='Время')),
                ('proc', models.TextField(max_length=350, verbose_name='Процедура')),
                ('kabinet', models.TextField(max_length=50, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Книжка',
                'verbose_name_plural': 'Книжки',
            },
        ),
    ]
