# Generated by Django 4.2 on 2023-06-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userdailyschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdailyschedule',
            unique_together=set(),
        ),
    ]
