# Generated by Django 4.2 on 2023-06-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_scheduledaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledaily',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
