# Generated by Django 4.2 on 2023-06-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_userdailyschedule_schedule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Procbook',
        ),
    ]
