# Generated by Django 4.2 on 2023-06-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
    ]
