# Generated by Django 4.2 on 2023-06-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyschedule',
            name='weekday',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=9),
        ),
    ]
