# Generated by Django 4.2 on 2023-06-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_userdailyschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyschedule',
            name='weekday',
            field=models.CharField(choices=[('понедельник', 'Понедельник'), ('вторник', 'Вторник'), ('среда', 'Среда'), ('четверг', 'Четверг'), ('пятница', 'Пятница'), ('суббота', 'Суббота'), ('воскресенье', 'Воскресенье')], max_length=11),
        ),
    ]
