# Generated by Django 4.2 on 2023-06-25 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_userdailyschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posters',
            name='image',
            field=models.ImageField(default='default.png', upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userdailyschedule',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdailyschedule',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='userdailyschedule',
            name='schedule',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
