# Generated by Django 4.2 on 2023-06-27 22:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0032_alter_review_options_alter_scheduledaily_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDailySchedule',
            new_name='Личноерасписание',
        ),
        migrations.AlterModelOptions(
            name='личноерасписание',
            options={'verbose_name': 'Личное расписание пользователей', 'verbose_name_plural': 'Личное расписание пользователей'},
        ),
    ]
