# Generated by Django 4.2 on 2023-06-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_userdailyschedule_личноерасписание_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='личноерасписание',
            options={'verbose_name': 'Личное расписание', 'verbose_name_plural': 'Личное расписание'},
        ),
    ]
