# Generated by Django 4.2 on 2023-06-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_личноерасписание_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledaily',
            name='деньнедели',
            field=models.IntegerField(choices=[('понедельник', 'Понедельник'), ('вторник', 'Вторник'), ('среда', 'Среда'), ('четверг', 'Четверг'), ('пятница', 'Пятница'), ('суббота', 'Суббота'), ('воскресенье', 'Воскресенье')], default=0),
        ),
        migrations.AlterField(
            model_name='личноерасписание',
            name='деньнедели',
            field=models.IntegerField(choices=[('понедельник', 'Понедельник'), ('вторник', 'Вторник'), ('среда', 'Среда'), ('четверг', 'Четверг'), ('пятница', 'Пятница'), ('суббота', 'Суббота'), ('воскресенье', 'Воскресенье')], default=0),
        ),
    ]
