# Generated by Django 4.2 on 2023-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_scheduledaily_деньнедели'),
    ]

    operations = [
        migrations.AlterField(
            model_name='личноерасписание',
            name='деньнедели',
            field=models.IntegerField(choices=[('понедельник', 'Понедельник'), ('вторник', 'Вторник'), ('среда', 'Среда'), ('четверг', 'Четверг'), ('пятница', 'Пятница'), ('суббота', 'Суббота'), ('воскресенье', 'Воскресенье')], default='понедельник'),
        ),
    ]
