# Generated by Django 4.2 on 2023-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_личноерасписание_деньнедели'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_choice', models.CharField(choices=[('лечение', 'Лечение'), ('оздоровление', 'Оздоровление'), ('отдых', 'Отдых')], max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
