# Generated by Django 4.2 on 2023-07-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='goal_choice',
            field=models.CharField(choices=[('лечение', 'Лечение'), ('оздоровление', 'Оздоровление'), ('отдых', 'Отдых')], default='лечение', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='visit_choice',
            field=models.CharField(choices=[('впервые', 'Впервые'), ('повторно', 'Повторно'), ('более двух раз', 'Более двух раз')], default='впервые', max_length=50),
        ),
    ]
