# Generated by Django 4.2 on 2023-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_review_goal_choice_review_visit_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='istochnik',
            field=models.CharField(choices=[('', ''), ('знакомые', 'Знакомые'), ('реклама', 'Реклама'), ('другой вариант', 'Другой вариант')], default='', max_length=50),
        ),
    ]
