# Generated by Django 4.2 on 2023-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_review_istochnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='goal_choice',
            field=models.CharField(choices=[('', ''), ('лечение', 'Лечение'), ('оздоровление', 'Оздоровление'), ('отдых', 'Отдых')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_choice',
            field=models.CharField(choices=[('', ''), ('впервые', 'Впервые'), ('повторно', 'Повторно'), ('более двух раз', 'Более двух раз')], default='', max_length=50),
        ),
    ]
