# Generated by Django 4.2 on 2023-07-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_review_goal_choice_alter_review_visit_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='istochnik',
            field=models.CharField(max_length=50),
        ),
    ]
