# Generated by Django 4.2 on 2023-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_review_istochnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gruppa',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='kak_preobletali',
            field=models.CharField(choices=[('', ''), ('полная стоимость', 'Полная стоимость'), ('льготная стоимость', 'Льготная стоимость')], default='', max_length=50),
        ),
    ]
