# Generated by Django 4.2 on 2023-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_review_gruppa_review_kak_preobletali'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_rating',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='treatment_rating',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=50),
        ),
    ]
