# Generated by Django 4.2 on 2023-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_review_service_rating_review_treatment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service_rating',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment_rating',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=50),
        ),
    ]
