# Generated by Django 4.2 on 2023-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_review_service_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pitanie',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='projivanie',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='service_rating',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment_rating',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50),
        ),
    ]
