# Generated by Django 4.2 on 2023-07-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_review_pitanie_review_projivanie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service_rating',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Сервис'),
        ),
    ]
