# Generated by Django 4.2 on 2023-07-03 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0050_alter_review_service_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='goal_choice',
            field=models.CharField(choices=[('', ''), ('лечение', 'Лечение'), ('оздоровление', 'Оздоровление'), ('отдых', 'Отдых')], default='', max_length=50, verbose_name='Цель выбора здравницы'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gruppa',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=50, verbose_name='Группа ограничений трудоспособности'),
        ),
        migrations.AlterField(
            model_name='review',
            name='istochnik',
            field=models.CharField(max_length=100, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='review',
            name='kak_preobletali',
            field=models.CharField(choices=[('', ''), ('полная стоимость', 'Полная стоимость'), ('льготная стоимость', 'Льготная стоимость')], default='', max_length=50, verbose_name='Как приобретали путевку'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pitanie',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка качества питания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='projivanie',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка качества проживания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service_rating',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка качества сервиса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment_rating',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка качества лечения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_choice',
            field=models.CharField(choices=[('', ''), ('впервые', 'Впервые'), ('повторно', 'Повторно'), ('более двух раз', 'Более двух раз')], default='', max_length=50, verbose_name='Посещаете данную здравницу'),
        ),
    ]
