# Generated by Django 4.2 on 2023-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_review_date_alter_review_goal_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='kval_med_pers',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка качества квалификации медицинского персонало'),
        ),
        migrations.AddField(
            model_name='review',
            name='soc_deatel',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка качества социокультурной деятельности'),
        ),
    ]
