# Generated by Django 4.2 on 2023-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_review_kval_med_pers_review_soc_deatel'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='obsluj',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка культуры обсуживающего персонала'),
        ),
        migrations.AddField(
            model_name='review',
            name='sred_med',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка культуры обслуживания среднего медицинского персонала'),
        ),
        migrations.AddField(
            model_name='review',
            name='vrach',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка культуры обслуживания врачей'),
        ),
        migrations.AlterField(
            model_name='review',
            name='istochnik',
            field=models.CharField(choices=[('', ''), ('знакомые', 'Знакомые'), ('реклама', 'Реклама'), ('другой вариант', 'Другой вариант')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='kval_med_pers',
            field=models.CharField(choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, verbose_name='Оценка качества квалификации медицинского персонала'),
        ),
    ]
