# Generated by Django 4.2 on 2023-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_review_obsluj_review_sred_med_review_vrach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='kak_v_celom',
            field=models.CharField(choices=[('', ''), ('удовлетворительно', 'Удовлетворительно'), ('хорошо', 'Хорошо'), ('отлично', 'Отлично')], default='', max_length=50, verbose_name='Как в целом Вы можете оценить впечатления от пребывания в санатории'),
        ),
        migrations.AddField(
            model_name='review',
            name='kakova_ver',
            field=models.CharField(choices=[('', ''), ('0', 'ни в коем случае'), ('1', 'Удовлетворительно'), ('2', 'Хорошо'), ('3', 'Отлично'), ('4', 'Отлично'), ('5', 'обязательно порекомендую')], default='', max_length=50, verbose_name='Какова вероятность что вы порекомендуете данную здравницу друзьям'),
        ),
        migrations.AlterField(
            model_name='review',
            name='istochnik',
            field=models.CharField(max_length=100, verbose_name='Источник'),
        ),
    ]
