# Generated by Django 4.2 on 2023-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_review_kak_v_celom_review_kakova_ver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='review',
            name='gender',
            field=models.CharField(choices=[('м', 'М'), ('ж', 'Ж')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='review',
            name='opros',
            field=models.CharField(choices=[('', ''), ('0', 'ни в коем случае'), ('1', 'Вряд ли'), ('2', 'Возможно'), ('3', 'Скорее всего да'), ('4', 'Расскажу конечно'), ('5', 'обязательно порекомендую')], default='', max_length=50, verbose_name='Какова вероятность что вы порекомендуете данную здравницу друзьям'),
        ),
        migrations.AlterField(
            model_name='review',
            name='kakova_ver',
            field=models.CharField(choices=[('', ''), ('0', 'ни в коем случае'), ('1', 'Вряд ли'), ('2', 'Возможно'), ('3', 'Скорее всего да'), ('4', 'Расскажу конечно'), ('5', 'обязательно порекомендую')], default='', max_length=50, verbose_name='Какова вероятность что вы порекомендуете данную здравницу друзьям'),
        ),
    ]
