# Generated by Django 4.2 on 2023-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_review_age_alter_review_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.CharField(blank=True, choices=[('м', 'М'), ('ж', 'Ж'), ('', '')], default='', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='review',
            name='goal_choice',
            field=models.CharField(blank=True, choices=[('', ''), ('лечение', 'Лечение'), ('оздоровление', 'Оздоровление'), ('отдых', 'Отдых')], default='', max_length=50, null=True, verbose_name='Цель выбора здравницы'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gruppa',
            field=models.CharField(blank=True, choices=[('', ''), ('не имею', 'не имею'), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=50, null=True, verbose_name='Группа ограничений трудоспособности'),
        ),
        migrations.AlterField(
            model_name='review',
            name='istochnik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='review',
            name='kak_preobletali',
            field=models.CharField(blank=True, choices=[('', ''), ('полная стоимость', 'Полная стоимость'), ('льготная стоимость', 'Льготная стоимость')], default='', max_length=50, null=True, verbose_name='Как приобретали путевку'),
        ),
        migrations.AlterField(
            model_name='review',
            name='kak_v_celom',
            field=models.CharField(blank=True, choices=[('', ''), ('удовлетворительно', 'Удовлетворительно'), ('хорошо', 'Хорошо'), ('отлично', 'Отлично')], default='', max_length=50, null=True, verbose_name='Как в целом Вы можете оценить впечатления от пребывания в санатории'),
        ),
        migrations.AlterField(
            model_name='review',
            name='kakova_ver',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'ни в коем случае'), ('1', 'Вряд ли'), ('2', 'Возможно'), ('3', 'Скорее всего да'), ('4', 'Расскажу конечно'), ('5', 'обязательно порекомендую')], default='', max_length=50, null=True, verbose_name='Какова вероятность что вы порекомендуете данную здравницу друзьям'),
        ),
        migrations.AlterField(
            model_name='review',
            name='kval_med_pers',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка качества квалификации медицинского персонала'),
        ),
        migrations.AlterField(
            model_name='review',
            name='obsluj',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка культуры обсуживающего персонала'),
        ),
        migrations.AlterField(
            model_name='review',
            name='opros',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'ни в коем случае'), ('1', 'Вряд ли'), ('2', 'Возможно'), ('3', 'Скорее всего да'), ('4', 'Расскажу конечно'), ('5', 'обязательно порекомендую')], default='', max_length=50, null=True, verbose_name='Какова вероятность что вы порекомендуете данную здравницу друзьям'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pitanie',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка качества питания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='projivanie',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка качества проживания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service_rating',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка качества сервиса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='soc_deatel',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка качества социокультурной деятельности'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sred_med',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка культуры обслуживания среднего медицинского персонала'),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment_rating',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка качества лечения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='visit_choice',
            field=models.CharField(blank=True, choices=[('', ''), ('впервые', 'Впервые'), ('повторно', 'Повторно'), ('более двух раз', 'Более двух раз')], default='', max_length=50, null=True, verbose_name='Посещаете данную здравницу'),
        ),
        migrations.AlterField(
            model_name='review',
            name='vrach',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1 - Плохо'), ('2', '2 - Удовлетворительно'), ('3', '3 - Хорошо'), ('4', '4 - Очень хорошо'), ('5', '5 - Отлично')], default='', max_length=50, null=True, verbose_name='Оценка культуры обслуживания врачей'),
        ),
    ]
