# Generated by Django 4.2 on 2023-07-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_review_age_alter_review_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='отзыв'),
        ),
    ]
