# Generated by Django 4.2 on 2023-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Услуга',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('номер', models.IntegerField(blank=True, null=True)),
                ('название', models.CharField(max_length=200)),
                ('описание', models.TextField()),
                ('ед_измерения', models.CharField(max_length=50)),
                ('цена', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
