# Generated by Django 4.2 on 2023-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_услуга_дополнительная_информация'),
    ]

    operations = [
        migrations.AlterField(
            model_name='услуга',
            name='ед_измерения',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='услуга',
            name='название',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='услуга',
            name='цена',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
