# Generated by Django 4.2 on 2023-07-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_услуга_ед_измерения_alter_услуга_название_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='услуга',
            name='описание',
            field=models.TextField(blank=True, null=True),
        ),
    ]
