# Generated by Django 4.2 on 2023-07-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_review_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=1, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.CharField(blank=True, choices=[('м', 'М'), ('ж', 'Ж'), ('', '')], default='', max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
