# Generated by Django 4.2 on 2023-07-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_review_rating_alter_review_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'оценка 1'), ('2', 'оценка 2'), ('3', 'оценка 3'), ('4', 'оценка 4'), ('5', 'оценка 5')], default='', max_length=1, null=True, verbose_name='Оценка'),
        ),
    ]
