# Generated by Django 4.2 on 2023-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('', ''), ('оценка 1', 'оценка 1'), ('оценка 2', 'оценка 2'), ('оценка 3', 'оценка 3'), ('оценка 4', 'оценка 4'), ('оценка 5', 'оценка 5')], default='', max_length=10, null=True, verbose_name='Оценка'),
        ),
    ]
