# Generated by Django 4.2 on 2023-07-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('', ''), ('★', '1★'), ('★★', '2★'), ('★★★', '3★'), ('★★★★', '4★'), ('★★★★★', '5★')], default='', max_length=6, null=True, verbose_name='Оценка'),
        ),
    ]
